### ISSUE TITLE
Build & Release: Storage Framework & Doclea

### ISSUE THREAD

**Issue by FalkZ** [FalkZ/doclea#41]
As a developer I want to build and make a release of the current integration-branch.

- [ ] Build integration-branch
- [ ] Release integration-branch

**Comment by MzrW** [comment]
folgender patch musste gemacht werden:

``` diff
--- a/package.json
+++ b/package.json
@@ -6,8 +6,7 @@
   "scripts": {
     "build": "pnpm run build -r",
     "test": "pnpm run test -r",
-    "dev": "pnpm run dev -r",
-    "install": "pnpm install -r"
+    "dev": "pnpm run dev -r"
   },
   "devDependencies": {
     "@parcel/transformer-inline-string": "2.4.1",
```

neu müsste man `pnpm recursive install` aufrufen.

siehe https://github.com/pnpm/pnpm/issues/3245

**Comment by MzrW** [comment]
pnpm-lock.yaml müsste dieses nicht in die .gitignore datei
