### ISSUE TITLE
github-adapter: asynchronous loop in remove/rename directory fails

### ISSUE THREAD

**Issue by mikko-abad** [FalkZ/doclea#80]
file: GithubDirectoryEntry.ts
**await** storageElements[index].remove()

---

**expected behaviour**
Run remove method (which returns a Promise) sequentially

**actual behaviour**
case with `await`, the loop stops running after first iteration
![image](https://user-images.githubusercontent.com/55510815/167317260-a750f461-157a-403e-90ec-3867e5dd5876.png)
![image](https://user-images.githubusercontent.com/55510815/167317278-00a55527-e066-4746-bd3f-29e4473dadd4.png)

case without `await`, the loop runs all remove in parallel
![image](https://user-images.githubusercontent.com/55510815/167317317-c94ff21c-36ae-4d7d-a57f-6ee5c67d934c.png)
![image](https://user-images.githubusercontent.com/55510815/167317320-94a663bf-a1a8-41b7-9f31-238b1d2e36f0.png)

**Comment by FalkZ** [comment]
The awaited version look correct to me. I'll try it my self later.
